version: '3'

volumes:
  postgres_db:


services:
  django:
    build:
      context: .
      dockerfile: ./compose/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./docker/:/code/
  db:
    image: postgres:10.3
    restart: always
    volumes:
      - postgres_db:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
